import type { Metadata } from "next";
import { Inter, Source_Code_Pro } from "next/font/google";

import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";

const inter = Inter({ subsets: ['latin'] });
export const source_code_pro = Source_Code_Pro({ subsets: ['latin']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <>
    <html lang="en" suppressHydrationWarning>
      <head/>
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider
          attribute="data-theme"
          defaultTheme="light"
          disableTransitionOnChange>
        {children}
        </ThemeProvider>
      </body>
    </html>
    </>
  );
}
